version: '3'

services:
  db:
    image: postgres:9.6 # we will use postgres:19.5 image from docker hub for database
    container_name: db17
    environment:
      - POSTGRES_USER=odoo # Set value of postgres credential
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      # - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #   - odoo-db-data:/var/lib/postgresql/data/pgdata # set postgresql data persistence
    ports:
      - "5410:5432"
    
  odoo:
    image: odoo:10.0
    container_name: odoo17
    volumes:
    #  - ./addons-enterprise:/mnt/enterprise-addons # Mount volume between host and container, host_dir:container_dir
      - /home/abuabdirohman/Documents/addons-odoo10:/mnt/extra-addons
      # - /etc/config:/etc/odoo
      # - odoo-web-data:/var/lib/odoo
    ports:
      - "8017:8069" # this will create connection port between host and container, this means host_port:container_port
    depends_on:
      - db # set depends on postgresql db

# volumes:
#  odoo-web-data:
#  odoo-db-data: