version: "3.8"

services:
  mongo: 
    container_name: mongo
    image: mongo:4-xenial
    ports:
      - 27017:271017
  redis:
    container-name: redis
    image: redis:5
    ports:
      - 6379:6379
  java-docker:
    container_name: java-docker
    image: java-docker:1.0
    ports: 
      - 8080:8080
    depends_on:
      - redis
      - mongo

    environment:
      - NAME=Docker
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379