version: '3'

services:
 db:
   image: postgres:9.5 # we will use postgres:10 image from docker hub for database
   environment:
     - POSTGRES_USER=odoo # Set value of postgres credential
     - POSTGRES_PASSWORD=odoo
     - POSTGRES_DB=postgres
     - PGDATA=/var/lib/postgresql/data/pgdata
   volumes:
     - odoo-db-data:/var/lib/postgresql/data/pgdata # set postgresql data persistence
   ports:
     - "5413:5432"

 odoo:
   #image: odoo:13.0
   build: .
   volumes:
     - ./addons-enterprise:/mnt/enterprise-addons # Mount volume between host and container, host_dir:container_dir
     - ./addons-extra:/mnt/extra-addons
     - ./config:/etc/odoo
     - odoo-web-data:/var/lib/odoo
     - addons-odoo:/usr/lib/python3/dist-packages/odoo/addons
   ports:
     - "9013:8069" # this will create connection port between host and container, this means host_port:container_port
   depends_on:
     - db # set depends on postgresql db
   # environment:
   #   - HOST=localhost
   #   - PORT=5432
   #   - USER=odoo
   #   - PASSWORD=odoo
     
   # custom command
   # command: odoo -u jidoka_siakad_base -d ponpes_13

volumes:
 odoo-web-data:
 odoo-db-data:
 addons-odoo: