version: '3'

services:
  db:
    image: postgres:9.5 # we will use postgres:19.5 image from docker hub for database
    container_name: db15
    environment:
      - POSTGRES_USER=odoo # Set value of postgres credential
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata # set postgresql data persistence
    
  web:
    image: odoo:12.0
    container_name: odoo15
    volumes:
    #  - ./addons-enterprise:/mnt/enterprise-addons # Mount volume between host and container, host_dir:container_dir
      - /home/ubuntu/addons/gnbs-project-module:/mnt/extra-addons
      - /etc/config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - "80:8069" # this will create connection port between host and container, this means host_port:container_port
    depends_on:
      - db # set depends on postgresql db
   
  reverse:
    container_name: reverse
    # hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/config/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/certs:/etc/ssl/private
volumes:
 odoo-web-data:
 odoo-db-data: